### ISSUE TITLE
Better Enemy control

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Kamigakari-System#14]
Hello, I've tested your system and it is really cool.
However, I think it would be more comfortable if you enhance enemy controls on battle.

1. Can you add timing element to enemy's attack options, like talent of characters? I was a bit busy finding the right timing of enemies' timings.
2. Can you separate attack options' categories into two - Boss talent and normal attack options?
3. If it's possible, can you make an option for enemies to adapt damage automatically as chat buttons or macros, for gm, like characters do?

Thank you for your hard work. I hope you have a nice, cool summer.

안녕하세요, 시스템 잘 테스팅해봤습니다. 

정말 편하게 잘 썼습니다만, 혹시 에너미 조작을 조금 개선해주실 수 있을까요?

1. 에너미의 공격 옵션에 '타이밍' 속성을 넣어주셨으면 합니다. 캐릭터들처럼요. 에너미들이 보스 포함 평균 5, 6마리 정도 되다 보니 어느 타이밍에 뭘 써야하는 지 항상 헷갈려서요. 
2. 에너미의 공격 옵션을 보스 탤런트와 일반 공격 옵션으로 분류해주실 수 있을까요?
3. 에너미의 대미지를 캐릭터들에게 자동 적용해주는 채팅 버튼이나 매크로? 같은 것도 있으면 좋을 것 같습니다. 캐릭터들은 에너미들에게 자동 적용되는데, 에너미의 공격은 수동으로 계산 후에 적용해야 해서 살짝 번거로웠어요 

요즘 날도 더운데 건강하고 시원한 여름 보내시길 바랍니다. 감사합니다.

**Comment by ksx0330** [comment]
Thank you for using it. Improvements to enemy manipulation are a must-have topic, but the complexity of each timing was putting it aside because we didn't know what talent would be applied.

We will proceed with the improvement based on the issues you posted, but we have a few questions before proceeding.

1. "Timing" is already included in Enemy's attack, but I'd like you to tell me the timing that already exists and the timing that you're talking about.

2. What is the reason for separating Enemy's attack from her boss talent? Is there a difference between the two apart from the fact that the boss talent is recycled?

We will proceed with the automatic application of the damage.
Please wait a little longer.

I hope you stay healthy in this hot summer without harming your health.

사용해주셔서 감사합니다. 에너미 조작의 개선은 꼭 필요한 주제지만, 각 타이밍에 어떤 탤런트가 적용될지 모르니 그 복잡성으로 인해 미뤄두고 있는 형편이었습니다.

올려주신 이슈를 기반으로 하여 개선을 진행할 예정입니다만, 진행하기 이전에 질문점이 몇 가지 있습니다.

1. 에너미의 공격에 "타이밍"은 이미 들어가 있습니다만, 만약 이미 있는 타이밍과 말씀하시는 타이밍이 언제 쓰이는 타이밍인지 말씀해 주시면 좋겠습니다.

2. 에너미의 공격 행동과 보스 탤런트를 분리하는 이유가 무엇인가요? 보스 탤런트는 재활용된다는 점 이외에 둘 사이의 차이점이 있을까요?

대미지 자동 적용은 차차 진행해 나갈겁니다.
조금 긴 시간을 가지고 기다려주시길 바랍니다.

더운 여름 건강 해치지 말고 건강하게 지내시길 바랍니다.

**Comment by jbblily** [comment]
안녕하세요, 이제서야 확인했네요
설명이 부족한 부분이 있어서 보충해서 말씀드리겠습니다. 
1.  이 불편함은 token hud 모듈을 사용할 때 생각난 것입니다. 이미 타이밍 칸은 있지만, token hud 상에는 같은 카테고리 안에 들어가 있기 때문에 캐릭터처럼 어느 타이밍에 뭘 써야하는지 분류가 되어 있지 않아 헷갈렸기 때문입니다. 플레이어들은 자기 시트만 보면 되서 비교적 수월하지만 gm은 한번에 5~6마리의 에너미를 컨트롤하다보니 정말 헷갈리거든요. 플레이어 뿐만 아니라 GM이 컨트롤하는 에너미들도 각 타이밍별로 분류해서 볼 수 있으면 좋을 것 같습니다.

2. 이건 별로 필수적이지 않은 부분이라, 적절치 않다고 생각하면 제외해도 좋을 것 같습니다...! 몇몇 보스 탤런트들은 세션 종료 시 영문 정산에 보너스를 주기도 하고, 세션 당 1회만 쓸 수 있는 경우도 있고 해서 구분해서 보기편하라고... 가 그 이유입니다. 굳이 필요치 않다고 생각하면 반려해주셔도 좋을 것 같습니다. 

항상 꼼꼼한 확인 감사합니다.

**Comment by ksx0330** [comment]
Updated 1.1.0 version
